# Generated by Django 5.0.2 on 2024-09-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_chatmessage_sender_type_chatmessage_bot_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotContext',
        ),
    ]
