# Generated by Django 5.0.2 on 2024-10-24 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chatsession_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-session_started']},
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='session_ended',
        ),
    ]
